# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Dev Backend To Azure

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        export auto_ecole_db="mongodb+srv://dev:AutoEcole.TN@cluster0.ftvww.mongodb.net/<dbname>?retryWrites=true&w=majority"
        export auto_ecole_jwtPrivateKey="secretKe_y"
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'autoecolebackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_53d469ebb97e4145b5915d70cc15ae6e }}
        package: .
