# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy backend to App Serv 2 - auto-backend-ser2 V1.2

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        export auto_ecole_db="mongodb+srv://dev:AutoEcole.TN@cluster0.ftvww.mongodb.net/<dbname>?retryWrites=true&w=majority"
        export auto_ecole_jwtPrivateKey="secretKe_y"
        npm install
        npm run build --if-present

    - name: 'Deploy backend to App Serv 2'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'auto-backend-ser2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_080eb5f9da4a4da8a09416c463ccbaaa }}
        package: ./dist/
